server:
  port: 9000

spring:
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

jwt:
  secret: 158ba9c386a9eb4a3858c0b310c39d7ad2cd8f427b5b2fddf6f7984e71d96898
  expiration: 86400000 # a day
