server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: user-service
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:8000}/${DB_NAME:mydatabase}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234567}
    driver-class-name: org.postgresql.Driver
  

eureka:
  instance:
    prefer-ip-address: true
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVICE_URL:localhost:8761}/eureka/
