server:
  port: 8084

spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/ecommerce"
      database: ecommerce
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: order-service

eureka:
  instance:
    prefer-ip-address: true
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/