server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: order-service
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: "mongodb://${MONGO_USERNAME:mydatabase}:${MONGO_PASSWORD:1234567}@${MONGO_HOST:localhost}:${MONGO_PORT:8002}/${MONGO_DATABASE:mydatabase}?authSource=admin"
      
eureka:
  instance:
    prefer-ip-address: true
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVICE_URL:localhost:8761}/eureka/
