version: "3.7"
services:
  # ====================================================================================================================
  # POSTGRES USER SERVER
  # ====================================================================================================================
  pg-user:
    image: postgres:14-alpine
    container_name: pg-ecommerce-user
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: 1234567
    ports:
      - 8000:5432
    volumes:
      - ./.data/postgresql-user/data:/var/lib/postgresql-user/data
    networks:
      - dev-network
  # ====================================================================================================================
  # MYSQL PRODUCT SERVER
  # ====================================================================================================================
  pg-product:
    image: postgres:14-alpine
    container_name: pg-ecommerce-product
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: 1234567
    ports:
      - 8001:5432
    volumes:
      - ./.data/postgresql-product/data:/var/lib/postgresql-product/data
    networks:
      - dev-network
  # ====================================================================================================================
  # MONGO SERVER
  # ====================================================================================================================
  mongodb:
    image: mongo:jammy
    container_name: ecommerce-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mydatabase
      MONGO_INITDB_ROOT_PASSWORD: 1234567
    ports:
      - 8002:27017
    volumes:
      - ./.data/mongodb/data:/data/db
    networks:
      - dev-network
  # ======================================================================================================================
  # REDE
  # ======================================================================================================================
networks:
  dev-network:
    driver: bridge
