server:
  port: 8234

spring:
  application:
    name: api-gateway
  output:
    ansi:
      enabled: ALWAYS
 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 158ba9c386a9eb4a3858c0b310c39d7ad2cd8f427b5b2fddf6f7984e71d96898
  expiration: 86400000 # a day
