server:
  port: 8081

spring:
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  application:
    name: product-service

eureka:
  instance:
    prefer-ip-address: true
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/